kind: pipeline
name: default

steps:
- name: Build
  image: plugins/docker
  settings:
    repo: chrishsieh/drone-volume-cache
    dockerfile: ./Dockerfile
    context: .
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    tags:
      - latest
